config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  scope "(:locale)", locale: /en|ru/ do    
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      passwords:     'users/passwords',
      registrations: 'users/registrations',
      sessions:      'users/sessions',
    }

    resources :lists do
      resources :tasks
    end

    root to: 'lists#main_page'
  end
end

app/models/list.rb
class List < ApplicationRecord
  has_many   :tasks, dependent: :destroy
  belongs_to :user
  validates  :title, presence: true, uniqueness: { scope: :user_id }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list , only: [:show, :edit, :update, :destroy, :list_tasks]
  before_action :set_lists, only: [:main_page, :index, :create, :update, :destroy]
  

  def main_page
    respond_to(&:html)
  end

  def index
    respond_to do |format|
      format.js { render 'list_index.js.erb' }
    end
  end

  def list_tasks
    @tasks = @list.tasks.all
    respond_to(&:js)
  end

  def show
    respond_to(&:js)
  end

  def new
    @list = List.new
    respond_to(&:js)
  end

  def edit
    respond_to(&:js)
  end

  def create
    @list = current_user.lists.new(list_params)
    respond_to do |format|
      if @list.save
        format.js
        format.json { render :show, status: :created, location: @list }
      else
        set_flash_error(@list)
        format.js { render 'shared/notice.js.erb' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @list.update(list_params)
        format.js
        format.json { render :show, status: :ok, location: @list }
      else
        set_flash_error(@list)
        format.js { render 'shared/notice.js.erb' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @list.destroy
    respond_to do |format|
      # format.html { redirect_to root_path, notice: 'List was successfully deleted.' }
      format.js # { render 'list_index.js.erb' }
      format.json { head :no_content }
    end
  end

  private
    def set_list
      @list = current_user.lists.find(params[:id])
    end

    def set_lists
      @lists = current_user.lists.all
    end

    def list_params
      params.require(:list).permit(:title, :user_id)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_create.slim
li id="list-#{list.id}"
  = render 'list_string', list: list

app/views/lists/_edit.html.slim
== render 'form'

app/views/lists/_form.html.slim
= form_for @list, remote: true do |f|
  form
    .form-inline
      .form-group.mx-sm-3.mb-2
        = f.label :title, class: 'sr-only'
        = f.text_field :title, class: 'form-control', placeholder: t(:list_title), maxlength: '15'
      
      = f.button t(:save), class: 'btn btn-outline-primary mb-2'

app/views/lists/_index.html.slim
br
  .box.box-aqua
    .box-header.ui-sortable-handle 
      i.ion.ion-clipboard
      h1.box-title = t(:your_lists)
  
    .box-body
      ul#lists.todo-list.ui-sortable
        - @lists.each do |list|
           = render 'create', list: list
        .created-lists
    .box-footer.clearfix.no-border
      span.fa.fa-plus
      = link_to  t(:new_list), new_list_path, remote: true

app/views/lists/_list_string.slim
span
  = link_to list.title, list_tasks_path(list), remote: true
  .tools
    = link_to '', edit_list_path(list), remote: true, class:'fa fa-edit'
    = link_to '', list, data: { confirm: 'Are you sure?' }, method: :delete, remote: true, class:'fa fa-trash'

app/views/lists/_new.html.slim
== render 'form'

app/views/lists/create.js.erb
$('#mainModal').modal('hide');
$('#lists').append('<%= j render 'create', list: @list %>');

app/views/lists/destroy.js.erb
$('#list-<%= @list.id %>').fadeOut();

app/views/lists/edit.js.erb
$('#mainModal').modal("show");
$('.modal-title').html("<%= t(:edit_list) %>");
$('.form').html("<%= j (render 'edit') %>"); 

app/views/lists/list_index.js.erb
$('.list-index').html("<%= j render 'lists/index' %>");

app/views/lists/list_tasks.js.erb
$('.list-tasks').html("<%= j render 'lists/index' %>");
$('.list-tasks').slideDown(800);

app/views/lists/main_page.slim
= render 'shared/header'


#mainModal.modal.fade aria-hidden="true" aria-labelledby="mainModalLabel" role="dialog" tabindex="-1" 
  .modal-dialog role="document" 
    .modal-content
      .modal-header
        h5#mainModalLabel.modal-title
        .right-close-button
          button.btn.btn-secondary data-dismiss="modal" type="button" 
            = t(:close)
      .modal-body
        .form


.container
  .row
    .col-xs-12.col-sm-12.col-lg-4
      = render 'index'
    .col-xs-12.col-sm-12.col-lg-8
      .tasks-index

app/views/lists/new.js.erb
$('#mainModal').modal("show");
$('.modal-title').html("<%= t(:new_list) %>");
$('.form').fadeIn("slow");
$('.form').html("<%= j (render 'new') %>");

app/views/lists/update.js.erb
$('#mainModal').modal('hide');
$('#list-<%= @list.id %>').html('<%= j render 'list_string', list: @list %>');