config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  scope "(:locale)", locale: /en|ru/ do    
    devise_for :users, skip: :omniauth_callbacks, controllers: {
      passwords:     'users/passwords',
      registrations: 'users/registrations',
      sessions:      'users/sessions',
    }

    resources :lists do
      resources :tasks
    end

    root to: 'lists#main_page'
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  has_one_attached :document
  validates  :content, presence: true

  def deadline_soon?
    if self.deadline && self.important
      task_deadline = utc_client_deadline
      task_deadline <= Time.current.utc + 2.hours
    else
      false
    end
  end

  def client_deadline(client_timezone)
    self.deadline + utc_client_deadline.in_time_zone(client_timezone).utc_offset
  end

  def deadline_argument(arg)
    self.client_deadline(self.timezone).to_time.strftime(arg)
  end

  private

  def utc_client_deadline
    self.deadline - self.deadline.in_time_zone(self.timezone).utc_offset
  end
end

##NOTE
## get the timezone offset in hours:
## Task.last.deadline.strftime('%z')[0..2].to_i 

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_list
  before_action :set_client_timezone, only: [:create, :update]
  
  rescue_from Timezone::Error::GeoNames, with: :timezone_connection_problems

  def index
    @tasks = @list.tasks.order(:status, important: :desc)
  end

  def show; end

  def new
    @task = Task.new
    respond_to(&:js)
  end

  def edit
    respond_to(&:js)
  end

  def create
    @task = @list.tasks.new(task_params)
    @task.timezone = @client_timezone
    respond_to do |format|  
      if @task.save
        format.js
        format.json { render :show, status: :created, location: @task }
      else
        set_flash_error(@task)
        format.js { render 'shared/notice.js.erb' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @task.assign_attributes(task_params)
    @task.timezone = @client_timezone
    respond_to do |format|
      if @task.save
        format.js
        format.json { render :show, status: :ok, location: @task }
      else
        set_flash_error(@task)
        format.js { render 'shared/notice.js.erb' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      # format.html { redirect_to root_path, notice: 'Task was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end

  private
    def set_client_timezone
      loc = request.location
      lat, lng = loc.latitude, loc.longitude 
      lat = 50 if lat == nil
      lng = 30 if lng == nil

      @client_timezone = Timezone.lookup(lat, lng).name
    end

    def set_task
      @task = Task.find(params[:id])
    end

    def set_list
      @list = List.find(params[:list_id])
    end

    def task_params
      params.require(:task).permit(:content, :status, :important, :deadline, :description, :document, :list_id)
    end

    def timezone_connection_problems
      flash[:alert] = "We have some problems with connecton, please try again later."
      respond_to do |format| 
        format.js { render 'shared/notice.js.erb' }
      end
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_create.slim
- if task.status
  li.text-line-through  id="task-#{task.id}"
    = render 'task_string', task: task
- else
  li id="task-#{task.id}"
    = render 'task_string', task: task

app/views/tasks/_edit.html.slim
== render 'form'

app/views/tasks/_form.html.slim
= form_for [@list, @task], remote: true do |f|
  .mx-auto
    .form-row      
      .col-5
        = f.label :content, class: 'sr-only'
        = f.text_field :content, class: 'form-control', placeholder: t(:task_content), maxlength: '35'
      .col-4  
        = f.label :deadline, class: 'sr-only'
        = f.text_field :deadline, class: 'datetimepicker form-control', placeholder: t(:task_deadline), readonly: 'true' 
      .col-3
        = f.button t(:save), class: 'btn btn-outline-primary mb-2 ', id: 'ok', data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Save" }
  .form-row
    .col-9
      = f.label :description, class: 'sr-only'
      = f.text_area :description, class: 'form-control', placeholder: 'Task Description' 
    .col-3
      - if params[:action] == 'edit'
        .form-row   
          .form-inline
            = f.check_box :status, class: 'form-check-input'
            br
            = f.label t(:status), class: 'form-check-label', id: 'status-checkbox' 
      .form-row  
        .form-inline
          = f.check_box :important, class: 'form-check-input'
          br
          = f.label t(:important), class: 'form-check-label', id: 'important-checkbox'
  .form-row
    .col.pt-2
      = f.file_field :document
      

app/views/tasks/_index.html.slim
br
  .box.box-aqua
    .box-header.ui-sortable-handle
      i.ion.ion-clipboard
      h1.box-title 
        = @list.title
  
    .box-body
      ul#tasks.todo-list.ui-sortable
        - @tasks.each do |task|
           = render 'create', task: task
        .created-task
    .box-footer.clearfix.no-border
      span.fa.fa-plus
      = link_to t(:new_task), new_list_task_path, remote: true

app/views/tasks/_new.html.slim
== render 'form'

app/views/tasks/_task_string.slim
= form_for [@list, task], html:{class: 'check-edit'}, remote: true do |f|
  = f.check_box :status, id: "status-check-#{@list.id}-#{task.id}", class: "check"  
  
.task-content = link_to "#{task.content}", '#', remote: true, class:'task-popover', "data-toggle" => "popover", 
  "title" => "Task Description","data-content" => "#{task.description}", "data-trigger" => "hover"

- if task.deadline
  .task-deadline.d-none.d-sm-inline
    .label.label-danger
      .fa.fa-clock-o
      i
        = " #{task.deadline_argument('%d %b %Y %H:%M')}"

.tools
  - if task.document.attached?
    = link_to '', rails_blob_path(task.document, disposition: 'attachment'), class: 'fa fa-download task-popover',
    "data-toggle" => "popover", "title" => "Download attachment","data-content" => "#{task.document.filename}", "data-trigger" => "hover"
  = link_to '', edit_list_task_path(@list, task), remote: true, class: 'fa fa-edit'
  = link_to '', [@list, task], data: { confirm: 'Are you sure?' }, remote: true, method: :delete, class: 'fa fa-trash'

javascript:   
  $('.task-popover').popover({
    trigger: 'hover'  
  })
  

app/views/tasks/create.js.erb
$('#mainModal').modal('hide');
$('#tasks').add(".some-task-<%= @task.id %>").append('<%= j render 'create', task: @task %>');

app/views/tasks/destroy.js.erb
$('#task-<%= @task.id %>').fadeOut();

app/views/tasks/edit.js.erb
$('#mainModal').modal('show');
$('.modal-title').html("<%= t(:edit_task) %>");
$('.form').html("<%= j (render 'tasks/edit') %>");

date = new Date();

$('.datetimepicker').datetimepicker({
   minDate:date
});

app/views/tasks/index.js.erb
$('.tasks-index').html("<%= j (render 'tasks/index') %>")

app/views/tasks/new.js.erb
$('#mainModal').modal('show');
$('.modal-title').html("<%= t(:new_task) %>");
$('.form').html("<%= j (render 'tasks/new') %>");

date = new Date();

$('.datetimepicker').datetimepicker({
   minDate:date,
   minTime:date.getTime()
});

app/views/tasks/update.js.erb
var task_element = $('#task-<%= @task.id %>');

$('#mainModal').modal('hide');
task_element.html('<%= j render 'task_string', task: @task %>');

<% if @task.status %>
  task_element.addClass('text-line-through');
<% else %>
  task_element.removeClass('text-line-through');
<% end %>